__title__ = 'Mayan EDMS'
__version__ = '4.4.1'
__build__ = 0x040401
__build_string__ = 'v4.4-29-g73084bd04a_Thu Jan 19 09:56:23 2023 -0500'
__django_version__ = '3.2'
__author__ = 'Roberto Rosario'
__author_email__ = 'roberto.rosario@mayan-edms.com'
__description__ = 'Free Open Source Electronic Document Management System'
__license__ = 'Apache 2.0'
__copyright_short__ = '2011 Roberto Rosario'
__copyright__ = '{} {}'.format('Copyright', __copyright_short__)
__website__ = 'https://www.mayan-edms.com'
